/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Niveis;
import Modelos.*;
import java.awt.HeadlessException;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author robsom.mathei
 */
public class Nivel2 extends javax.swing.JFrame {
Personagem personagem;
int ataca;
Inimigo nivel2 = new Inimigo();    

    /**
     * Creates new form Nivel2
     */
    public Nivel2(Personagem personagem) {
        initComponents();
        this.personagem=personagem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomedoinimigo = new javax.swing.JTextField();
        txtNomePersonagem = new javax.swing.JTextField();
        lblAtaqueInimigo = new javax.swing.JLabel();
        lblVidaInimigo = new javax.swing.JLabel();
        lblAtaqueInimigo2 = new javax.swing.JLabel();
        lblVidaInimigo2 = new javax.swing.JLabel();
        txtAtaqueInimigo = new javax.swing.JTextField();
        txtVidaInimigo = new javax.swing.JTextField();
        txtAtaquePersonagem = new javax.swing.JTextField();
        txtVidaPersonagem = new javax.swing.JTextField();
        btnQuemAtaca = new javax.swing.JButton();
        btnAvança = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAtaqueInimigo.setText("Ataque:");

        lblVidaInimigo.setText("Vida:");

        lblAtaqueInimigo2.setText("Ataque:");

        lblVidaInimigo2.setText("Vida:");

        txtAtaqueInimigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAtaqueInimigoActionPerformed(evt);
            }
        });

        txtVidaPersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVidaPersonagemActionPerformed(evt);
            }
        });

        btnQuemAtaca.setText("Quem ataca?");

        btnAvança.setText("Avança>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblVidaInimigo)
                                .addGap(25, 25, 25))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAtaqueInimigo)
                                .addGap(10, 10, 10)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAtaqueInimigo)
                            .addComponent(txtVidaInimigo))
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAtaqueInimigo2)
                            .addComponent(lblVidaInimigo2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAtaquePersonagem, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(txtVidaPersonagem)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNomedoinimigo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNomePersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAvança)
                            .addComponent(btnQuemAtaca, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomedoinimigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomePersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAtaqueInimigo)
                    .addComponent(lblAtaqueInimigo2)
                    .addComponent(txtAtaqueInimigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAtaquePersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVidaInimigo)
                    .addComponent(lblVidaInimigo2)
                    .addComponent(txtVidaInimigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVidaPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnQuemAtaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(btnAvança)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAtaqueInimigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAtaqueInimigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAtaqueInimigoActionPerformed

    private void txtVidaPersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVidaPersonagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVidaPersonagemActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvança;
    private javax.swing.JButton btnQuemAtaca;
    private javax.swing.JLabel lblAtaqueInimigo;
    private javax.swing.JLabel lblAtaqueInimigo2;
    private javax.swing.JLabel lblVidaInimigo;
    private javax.swing.JLabel lblVidaInimigo2;
    private javax.swing.JTextField txtAtaqueInimigo;
    private javax.swing.JTextField txtAtaquePersonagem;
    private javax.swing.JTextField txtNomePersonagem;
    private javax.swing.JTextField txtNomedoinimigo;
    private javax.swing.JTextField txtVidaInimigo;
    private javax.swing.JTextField txtVidaPersonagem;
    // End of variables declaration//GEN-END:variables
}
