/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Niveis;
import Modelos.*;
import java.awt.HeadlessException;
import java.util.Random;
import javax.swing.JOptionPane;
/**
 *
 * @author Usuario
 */
public class Nivel1 extends javax.swing.JFrame {
Personagem personagem;
int ataca;
Inimigo nivel1 = new Inimigo();
    /**
     * Creates new form Nivel1
     */
    public Nivel1(Personagem personagem) {
        initComponents();
        this.personagem=personagem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomePersonagem = new javax.swing.JTextField();
        txtAtaqueInimigo = new javax.swing.JTextField();
        txtVidaInimigo = new javax.swing.JTextField();
        lblAtaqueInimigo = new javax.swing.JLabel();
        lblVidaInimigo = new javax.swing.JLabel();
        txtNomeInimigo = new javax.swing.JTextField();
        txtAtaquePersonagem = new javax.swing.JTextField();
        txtVidaPersonagem = new javax.swing.JTextField();
        lblAtaqueInimigo1 = new javax.swing.JLabel();
        lblVidaInimigo1 = new javax.swing.JLabel();
        btnQuemAtaca = new javax.swing.JButton();
        btnAvanca = new javax.swing.JButton();
        btnTentar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtNomePersonagem.setEditable(false);

        txtAtaqueInimigo.setEditable(false);

        txtVidaInimigo.setEditable(false);

        lblAtaqueInimigo.setText("Ataque:");

        lblVidaInimigo.setText("Vida:");

        txtNomeInimigo.setEditable(false);

        txtAtaquePersonagem.setEditable(false);

        txtVidaPersonagem.setEditable(false);

        lblAtaqueInimigo1.setText("Ataque:");

        lblVidaInimigo1.setText("Vida:");

        btnQuemAtaca.setText("Quem ataca?");
        btnQuemAtaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuemAtacaActionPerformed(evt);
            }
        });

        btnAvanca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sign-right.png"))); // NOI18N
        btnAvanca.setText("Avançar");
        btnAvanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancaActionPerformed(evt);
            }
        });

        btnTentar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sign-sync.png"))); // NOI18N
        btnTentar.setText("Tentar novamente");
        btnTentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTentarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(lblAtaqueInimigo))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblVidaInimigo)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAtaqueInimigo, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(txtVidaInimigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblAtaqueInimigo1))
                            .addComponent(lblVidaInimigo1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAtaquePersonagem)
                            .addComponent(txtVidaPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnQuemAtaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNomeInimigo, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                .addGap(98, 98, 98)
                                .addComponent(txtNomePersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnTentar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAvanca)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomePersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeInimigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAtaqueInimigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAtaqueInimigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVidaInimigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVidaInimigo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAtaquePersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAtaqueInimigo1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVidaPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVidaInimigo1))))
                .addGap(29, 29, 29)
                .addComponent(btnQuemAtaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvanca)
                    .addComponent(btnTentar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        mostrarInimigo();
        mostrarPersonagem();
        btnTentar.setEnabled(false);
        btnAvanca.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnQuemAtacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuemAtacaActionPerformed
        // TODO add your handling code here:
        Random gerador = new Random();
        ataca = gerador.nextInt(2);
        try{
            
            if (ataca==0) {
                JOptionPane.showMessageDialog(this, "Você ataca!");
                int vida = perdeVida(personagem, nivel1);
                if (vida > 0) {
                txtVidaInimigo.setText(String.valueOf(vida));
                } else {
                  txtVidaInimigo.setText(String.valueOf(0));
                  JOptionPane.showMessageDialog(this, "Você ganhou!");
                  btnQuemAtaca.setEnabled(false);
                  btnAvanca.setEnabled(true);
                }
            } else {
               JOptionPane.showMessageDialog(this, "O inimigo ataca!");
               int vida = perdeVida(personagem, nivel1);
               if (vida >0) {
               txtVidaPersonagem.setText(String.valueOf(vida));
               } else {
                  txtVidaPersonagem.setText(String.valueOf(0));
                  JOptionPane.showMessageDialog(this, "Você perdeu!");
                  btnQuemAtaca.setEnabled(false);
                  btnTentar.setEnabled(true);
               }

            }
        
        }catch(HeadlessException ex){
            
        }
    }//GEN-LAST:event_btnQuemAtacaActionPerformed

    private void btnTentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTentarActionPerformed
        // TODO add your handling code here:
        mostrarInimigo();
        mostrarPersonagem();
        btnTentar.setEnabled(false);
        btnAvanca.setEnabled(false);
        btnQuemAtaca.setEnabled(true);
    }//GEN-LAST:event_btnTentarActionPerformed

    private void btnAvancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnAvancaActionPerformed

   
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
private void mostrarInimigo() {
    Random gerador = new Random();
    nivel1.setNome("Inimigo Nível 1");
    nivel1.setNivel(1);
    nivel1.setVida(100);
    nivel1.setAtaque(gerador.nextInt(50)+1);
    txtNomeInimigo.setText(nivel1.getNome());
    txtAtaqueInimigo.setText(String.valueOf(nivel1.getAtaque()));
    txtVidaInimigo.setText(String.valueOf(nivel1.getVida()));
}
private void mostrarPersonagem(){
    personagem.setVida(100);
    personagem.getAtaque();
    txtNomePersonagem.setText(personagem.getNome());
    txtAtaquePersonagem.setText(String.valueOf(personagem.getAtaque()));
    txtVidaPersonagem.setText(String.valueOf(personagem.getVida()));   
}
private int perdeVida(Personagem p, Inimigo i) {
    if (ataca==0) {
        i.setVida(i.getVida()-p.getAtaque());
        return i.getVida();
    } else {
        p.setVida(p.getVida() - i.getAtaque());
        return p.getVida();
    }
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvanca;
    private javax.swing.JButton btnQuemAtaca;
    private javax.swing.JButton btnTentar;
    private javax.swing.JLabel lblAtaqueInimigo;
    private javax.swing.JLabel lblAtaqueInimigo1;
    private javax.swing.JLabel lblVidaInimigo;
    private javax.swing.JLabel lblVidaInimigo1;
    private javax.swing.JTextField txtAtaqueInimigo;
    private javax.swing.JTextField txtAtaquePersonagem;
    private javax.swing.JTextField txtNomeInimigo;
    private javax.swing.JTextField txtNomePersonagem;
    private javax.swing.JTextField txtVidaInimigo;
    private javax.swing.JTextField txtVidaPersonagem;
    // End of variables declaration//GEN-END:variables
}
