/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Niveis;
import Modelos.*;
import Modelos.CaixaDeDialogo;
import java.awt.Color;
import java.awt.HeadlessException;
import java.util.Random;
/**
 *
 * @author Usuario
 */
public class Nivel3 extends javax.swing.JFrame {
Personagem personagem;
int ataca;
int ataque;
int vidaOriginal;
int vidaInimigo;
Inimigo nivel3 = new Inimigo();
Random gerador = new Random(); 

    /**
     * Creates new form Nivel3
     */
    public Nivel3(Personagem personagem) {
        initComponents();
        this.personagem=personagem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAtaquePersonagem = new javax.swing.JTextField();
        txtVidaPersonagem = new javax.swing.JTextField();
        txtNomePersonagem = new javax.swing.JTextField();
        barVidaPersonagem = new javax.swing.JProgressBar();
        lblAtaqueInimigo2 = new javax.swing.JLabel();
        lblVidaInimigo2 = new javax.swing.JLabel();
        txtAtaqueInimigo = new javax.swing.JTextField();
        txtVidaInimigo = new javax.swing.JTextField();
        txtNomeInimigo = new javax.swing.JTextField();
        barVidaInimigo = new javax.swing.JProgressBar();
        lblAtaqueInimigo = new javax.swing.JLabel();
        lblVidaInimigo = new javax.swing.JLabel();
        txtAtaquePersonagem1 = new javax.swing.JTextField();
        txtVidaPersonagem1 = new javax.swing.JTextField();
        txtNomePersonagem1 = new javax.swing.JTextField();
        barVidaPersonagem1 = new javax.swing.JProgressBar();
        lblAtaqueInimigo3 = new javax.swing.JLabel();
        lblVidaInimigo3 = new javax.swing.JLabel();
        btnQuemAtaca = new javax.swing.JButton();

        txtAtaquePersonagem.setEditable(false);

        txtVidaPersonagem.setEditable(false);

        txtNomePersonagem.setEditable(false);

        barVidaPersonagem.setStringPainted(true);

        lblAtaqueInimigo2.setText("Ataque:");

        lblVidaInimigo2.setText("Vida:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAtaqueInimigo.setEditable(false);

        txtVidaInimigo.setEditable(false);

        txtNomeInimigo.setEditable(false);

        barVidaInimigo.setStringPainted(true);

        lblAtaqueInimigo.setText("Ataque:");

        lblVidaInimigo.setText("Vida:");

        txtAtaquePersonagem1.setEditable(false);

        txtVidaPersonagem1.setEditable(false);

        txtNomePersonagem1.setEditable(false);

        barVidaPersonagem1.setStringPainted(true);

        lblAtaqueInimigo3.setText("Ataque:");

        lblVidaInimigo3.setText("Vida:");

        btnQuemAtaca.setText("Quem ataca?");
        btnQuemAtaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuemAtacaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(txtNomeInimigo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAtaqueInimigo)
                            .addComponent(lblVidaInimigo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVidaInimigo)
                            .addComponent(txtAtaqueInimigo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(barVidaInimigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtNomePersonagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAtaqueInimigo3)
                            .addComponent(lblVidaInimigo3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAtaquePersonagem1)
                            .addComponent(txtVidaPersonagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(barVidaPersonagem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(btnQuemAtaca, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNomePersonagem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAtaquePersonagem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblVidaInimigo3)
                                        .addComponent(txtVidaPersonagem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblAtaqueInimigo3)
                                        .addGap(26, 26, 26)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(barVidaPersonagem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNomeInimigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAtaqueInimigo)
                            .addComponent(txtAtaqueInimigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVidaInimigo)
                            .addComponent(txtVidaInimigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(barVidaInimigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(188, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(138, 138, 138)
                    .addComponent(btnQuemAtaca)
                    .addContainerGap(139, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuemAtacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuemAtacaActionPerformed
        // TODO add your handling code here:
        ataca = gerador.nextInt(2);
        try{
            if (ataca==0) {
                CaixaDeDialogo.obterinstancia().exibirMensagem("Você ataca!", "Ataque!", 'i');
                ataquePersonagem();
            } else {
                CaixaDeDialogo.obterinstancia().exibirMensagem("O inimigo ataca!", "Ataque!", 'i');;
                ataqueInimigo();
            }
        } catch(HeadlessException ex){
            CaixaDeDialogo.obterinstancia().exibirMensagem(ex.getMessage().toString(),"ERRO",'e');
        }
    }//GEN-LAST:event_btnQuemAtacaActionPerformed

private void mostrarInimigo() {
    nivel3.setNome("Inimigo Nível 3");
    nivel3.setNivel(2);
    vidaInimigo=140;
    nivel3.setVida(vidaInimigo);
    nivel3.setAtaque(gerador.nextInt(80)+1);
    txtNomeInimigo.setText(nivel3.getNome());
    txtAtaqueInimigo.setText(String.valueOf(nivel3.getAtaque()));
    txtVidaInimigo.setText(String.valueOf(nivel3.getVida()));
    barVidaInimigo.setMaximum(vidaInimigo);
    barVidaInimigo.setMinimum(0);
    barVidaInimigo.setValue(vidaInimigo);
    barVidaInimigo.setString(String.valueOf(vidaInimigo));
}

private void mostrarPersonagem(){
    txtNomePersonagem.setText(personagem.getNome());
    txtAtaquePersonagem.setText(String.valueOf(personagem.getAtaque()));
    txtVidaPersonagem.setText(String.valueOf(personagem.getVida())); 
    vidaOriginal=personagem.getVida();
    barVidaPersonagem.setMaximum(vidaOriginal);
    barVidaPersonagem.setMinimum(0);
    barVidaPersonagem.setValue(vidaOriginal);
    barVidaPersonagem.setString(String.valueOf(vidaOriginal));
}

private void resetPersonagemGanhou() {
        txtVidaPersonagem.setText(String.valueOf(vidaOriginal));
        txtAtaquePersonagem.setText(String.valueOf(personagem.getAtaque()));
        barVidaPersonagem.setMaximum(vidaOriginal);
        barVidaPersonagem.setMinimum(0);
        barVidaPersonagem.setValue(vidaOriginal);
        barVidaPersonagem.setForeground(Color.green);
        barVidaPersonagem.setString(String.valueOf(vidaOriginal));
}

private void resetPersonagemPerdeu() {
     personagem.setVida(vidaOriginal);
     txtVidaPersonagem.setText(String.valueOf(personagem.getVida()));
     barVidaPersonagem.setMaximum(vidaOriginal);
     barVidaPersonagem.setMinimum(0);
     barVidaPersonagem.setValue(vidaOriginal);
     barVidaPersonagem.setForeground(Color.green);
     barVidaPersonagem.setString(String.valueOf(vidaOriginal));
}

public void resetInimigo() {
    nivel3.setVida(vidaInimigo);
    txtVidaInimigo.setText(String.valueOf(vidaInimigo));
    barVidaInimigo.setMaximum(vidaInimigo);
    barVidaInimigo.setMinimum(0);
    barVidaInimigo.setForeground(Color.green);
    barVidaInimigo.setString(String.valueOf(vidaInimigo));
    barVidaInimigo.setValue(vidaInimigo);
}

private void ataquePersonagem() {
   int ataque = gerador.nextInt(20)+1;
    if (ataque >12){
      int ataca = personagem.getAtaque()/2;
      nivel3.setVida(nivel3.getVida()-ataca);
      CaixaDeDialogo.obterinstancia().exibirMensagem("O inimigo perdeu " + ataca + " de vida!", "ATAQUE CRÍTICO", 'i');
        if (nivel3.getVida() >0) {
           txtVidaInimigo.setText(String.valueOf(nivel3.getVida()));
           barVidaInimigo.setValue(nivel3.getVida());
           barVidaInimigo.setString(String.valueOf(nivel3.getVida()));
            if (barVidaInimigo.getValue() < vidaInimigo/2 ) {
                barVidaInimigo.setForeground(Color.YELLOW);
            }
            if (barVidaInimigo.getValue() < vidaInimigo/3 ) {
                barVidaInimigo.setForeground(Color.RED);
            }
        } else {
            voceGanhou();
        }
      }else {
        int ataca = personagem.getAtaque()/3;
        nivel3.setVida(nivel3.getVida()-ataca);
        CaixaDeDialogo.obterinstancia().exibirMensagem("O inimigo perdeu " + ataca + " de vida!", "ATAQUE FRACO", 'i');
        if (nivel3.getVida() > 0) {
        txtVidaInimigo.setText(String.valueOf(nivel3.getVida()));
        barVidaInimigo.setValue(nivel3.getVida());
        barVidaInimigo.setString(String.valueOf(nivel3.getVida()));
          if (barVidaInimigo.getValue() < vidaInimigo/2 ) {
                barVidaInimigo.setForeground(Color.YELLOW);
            }
            if (barVidaInimigo.getValue() < vidaInimigo/3 ) {
                barVidaInimigo.setForeground(Color.RED);
            }
        } else {
        voceGanhou();
        }
    }
}

private void ataqueInimigo() {
   int ataque = gerador.nextInt(20)+1;
    int vida = personagem.getVida();
        if (ataque >12){
          int ataca = nivel3.getAtaque()/2;
          personagem.setVida(personagem.getVida()-ataca);
          CaixaDeDialogo.obterinstancia().exibirMensagem("Você perdeu " + ataca + " de vida!", "ATAQUE CRÍTICO", 'i');
          if (personagem.getVida() > 0) {
            txtVidaPersonagem.setText(String.valueOf(personagem.getVida()));
            barVidaPersonagem.setValue(personagem.getVida());
            barVidaPersonagem.setString(String.valueOf(personagem.getVida()));
            if (barVidaPersonagem.getValue() < vida/2 ) {
                barVidaPersonagem.setForeground(Color.YELLOW);
            }
            if (barVidaPersonagem.getValue() < vida/3 ) {
                barVidaPersonagem.setForeground(Color.RED);
            }
        } else {
            vocePerdeu();
          }
        } else {
            int ataca = nivel3.getAtaque()/3;
            personagem.setVida(personagem.getVida()-ataca);
            CaixaDeDialogo.obterinstancia().exibirMensagem("Você perdeu " + ataca + " de vida!", "ATAQUE FRACO", 'i');
            if (personagem.getVida() > 0) {
            txtVidaPersonagem.setText(String.valueOf(personagem.getVida()));
            barVidaPersonagem.setValue(personagem.getVida());
            barVidaPersonagem.setString(String.valueOf(personagem.getVida()));
            if (barVidaPersonagem.getValue() < vida/2 ) {
                barVidaPersonagem.setForeground(Color.YELLOW);
            }
            if (barVidaPersonagem.getValue() < vida/3 ) {
                barVidaPersonagem.setForeground(Color.RED);
            }
        }else {
                vocePerdeu();
    }
  }
}

public void vocePerdeu() {
  txtVidaPersonagem.setText(String.valueOf(0));
  barVidaPersonagem.setValue(0);
  barVidaPersonagem.setString(String.valueOf(0));
  boolean escolha = CaixaDeDialogo.obterinstancia().pedirConfirmacao("Deseja tentar novamente?", "VOCÊ PERDEU!", 'i');
  if (escolha == true) {
     resetPersonagemPerdeu();
     resetInimigo();
  } else {
      System.exit(0);
  }  
}

public void voceGanhou() {
    txtVidaInimigo.setText(String.valueOf(0)); 
    barVidaInimigo.setValue(0);
    barVidaInimigo.setString(String.valueOf(0));
    nextNivel();
    boolean escolha = CaixaDeDialogo.obterinstancia().pedirConfirmacao("Deseja tentar o próximo nível?", "PARABÉNS VOCÊ GANHOU", 'i');
    if(escolha == true){
        Nivel3 tela = new Nivel3(personagem);
        tela.setVisible(true);
        this.dispose();   
    } else {
        resetPersonagemGanhou();
        mostrarInimigo();
    }
}

public void nextNivel(){
  personagem.setNivel(3);
  boolean escolha = CaixaDeDialogo.obterinstancia().escolherAumento("Deseja aumentar 10 XP de Vida ou de Atauqe?", "PARABÉNS VOCÊ PASSOU PARA O NÍVEL 3", 'i');  
  if (escolha ==true) {
      updateVida();
  } else {
      updateAtaque();
  }
}

public void updateVida() {
    vidaOriginal = vidaOriginal +10;
    personagem.setVida(vidaOriginal); 
}

public void updateAtaque() {
    personagem.setAtaque(personagem.getAtaque()+10);  
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barVidaInimigo;
    private javax.swing.JProgressBar barVidaPersonagem;
    private javax.swing.JProgressBar barVidaPersonagem1;
    private javax.swing.JButton btnQuemAtaca;
    private javax.swing.JLabel lblAtaqueInimigo;
    private javax.swing.JLabel lblAtaqueInimigo2;
    private javax.swing.JLabel lblAtaqueInimigo3;
    private javax.swing.JLabel lblVidaInimigo;
    private javax.swing.JLabel lblVidaInimigo2;
    private javax.swing.JLabel lblVidaInimigo3;
    private javax.swing.JTextField txtAtaqueInimigo;
    private javax.swing.JTextField txtAtaquePersonagem;
    private javax.swing.JTextField txtAtaquePersonagem1;
    private javax.swing.JTextField txtNomeInimigo;
    private javax.swing.JTextField txtNomePersonagem;
    private javax.swing.JTextField txtNomePersonagem1;
    private javax.swing.JTextField txtVidaInimigo;
    private javax.swing.JTextField txtVidaPersonagem;
    private javax.swing.JTextField txtVidaPersonagem1;
    // End of variables declaration//GEN-END:variables
}
